#!/bin/bash
main=scal2/ui_qt/starcal_qt.py
myDir=`dirname "$0"`
if [ ! -d ~/.starcal2 ] ; then
    "$myDir/run" scal2/ui_gtk/config_importer.py ## FIXME
fi
if [ "$1" = "-q" ] ; then
    shift
    "$myDir/run" $main "$@" 2>> error.log
else
    "$myDir/run" $main "$@"
fi


